### ISSUE TITLE
Cannot inject interface with a generic return method

### ISSUE THREAD

**Issue by cable729** [graphql-dotnet/conventions#11]
First of all, thanks for sharing this library with the public! I'm trying to introduce it to a new project, but I'm running into some trouble when injecting a simple interface with a generic return method. I'm using .NET 4.5. This error:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Cannot create an instance of GraphQL.Conventions.Adapters.Types.OutputObjectGraphType`1[T] because Type.ContainsGenericParameters is true.
  Source=mscorlib
  StackTrace:
   at System.RuntimeType.CreateInstanceCheckThis()
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.CreateTypeInstance[TType](Type type)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructType[TReturnType](Type template, GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveField(GraphFieldInfo fieldInfo)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveFields(GraphTypeInfo typeInfo, IComplexGraphType graphType)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructInterfaceType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveType(GraphTypeInfo typeInfo)
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveSchema(GraphSchemaInfo schemaInfo)
   at GraphQL.Conventions.Builders.SchemaConstructor`2.Build(TypeInfo[] schemaTypes)
   at GraphQL.Conventions.Builders.SchemaConstructor`2.Build(Type[] schemaTypes)
   at GraphQL.Conventions.Adapters.Engine.GraphQLEngine.BuildSchema(Type[] schemaTypes)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\caleb\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 12
```

is produced by this code:

```
using GraphQL.Conventions.Adapters.Engine;
using GraphQL.Conventions.Attributes.MetaData;
using GraphQL.Conventions.Types;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = new GraphQLEngine();
            engine.BuildSchema(typeof(SchemaDefinition<Query>));
        }
    }

    public class Query
    {
        public int WithDependency([Inject] IDependency d)
            => 3;
    }

    public interface IDependency
    {
        T Get<T>();
    }
}
```

In fact, if I remove the `[Inject]` attribute, it still fails.

I haven't been able to build the project yet. I'm going to update my .NET Core installation and try again, and see if I can't debug this. Visual Studio is wanting me to upgrade the .xproj's to the new version of .csproj's as well, but keeps failing.

**Comment by tlil** [comment]
Thanks – will take a look @cable729. Are you registering a dependency injector btw (not that that should influence this)?

FWIW, I'm working on some improvements here now anyway, so will take a look at this at the same time.

**Comment by cable729** [comment]
I tried it both with registration and without registration. Same results.

**Comment by tlil** [comment]
I've found the issue and will push a fix soon

**Comment by cable729** [comment]
Awesome, thanks! By the way, I'm trying to figure out what tools I can use in windows to debug this. Apparently Visual Studio 2017 requires upgrades from xproj to csproj now. I'm going to double check if Visual Studio 2015 works with xproj's still.

**Comment by tlil** [comment]
Yep, I'll sort that as part of https://github.com/graphql-dotnet/conventions/issues/10 ;)

**Comment by cable729** [comment]
Cool! As soon as I can open in visual studio I can start digging deeper and hopefully contribute back to this project.

Alternatively, I suppose I can try opening it on my mac like you do.

**Comment by cable729** [comment]
Okay, I uninstalled all previous .NET Core tooling and installed only the latest LTS (1.0.3) version, along with the latest VS15 tooling. Now I'm able to open it up (after a few tweaks like fixing the extra lines at the beginning of the two test .xproj's and a duplicate project.json dependency in the server tests -- which I'm sure is the issue you're about to push a fix for in #10).

**Comment by tlil** [comment]
Closed by https://github.com/graphql-dotnet/conventions/pull/12. Let me know if you experience any more problems with this @cable729. Will look at the tooling one separately.

**Comment by cable729** [comment]
Thank you! Super excited to start using your library at work.
