### ISSUE TITLE
Guid is not working for as property type for models used by  graphql queries. v0.17.2

### ISSUE THREAD

**Issue by tecsined** [graphql-dotnet/conventions#70]
Guid is not working for Ids in the models used by the queries

```
//Error HERE creating the schema
     var schema = new Schema { Query = new UserResultQuery() };

{System.ArgumentException: The GraphQL type for Field: 'Id' on parent type: 'UserResultType' could not be derived implicitly. 
 ---> System.ArgumentOutOfRangeException: The type: Guid cannot be coerced effectively to a GraphQL type
Parameter name: type
   at GraphQL.TypeExtensions.GetGraphTypeFromType(Type type, Boolean isNullable)
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   --- End of inner exception stack trace ---
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](Expression`1 expression, Boolean nullable, Type type)
  
Using this model and this query

  public class UserResult
   {
       public Guid Id { get; set; }

       public string Username { get; set; }
    
   }
  public class UserResultQuery : ObjectGraphType
   {
       public UserResultQuery()
       {
           Field<UserResultType>(
               "user",
               resolve: context => new UserResult
               {
                   Username = "Denis",
                   Id = new Guid()
               });
       }
   }
```

**Comment by huysentruitw** [comment]
Isn't that graphql-dotnet instead of graphql-conventions? If you want to use graphql-conventions, read the readme and check out the example (start [here](https://github.com/graphql-dotnet/conventions)).
